//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public System.Guid AccessoriesID { get; set; }
        public System.Guid AccessoriesTemplateID { get; set; }
        public System.Guid ProductID { get; set; }
        public Nullable<decimal> AccessoriesX { get; set; }
        public Nullable<decimal> AccessoriesY { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AccessoriesCreatedOn { get; set; }
        public string AccessoriesCreatedBy { get; set; }
        public Nullable<System.DateTime> AccessoriesUpdatedOn { get; set; }
        public string AccessoriesUpdatedBy { get; set; }
    
        public virtual AccessoriesTemplate AccessoriesTemplate { get; set; }
        public virtual Product Product { get; set; }
    }
}
