//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoriesTemplate
    {
        public AccessoriesTemplate()
        {
            this.Accessories = new HashSet<Accessory>();
        }
    
        public System.Guid AccssoriesTemplateID { get; set; }
        public string AccessoriesTemplateName { get; set; }
        public System.Guid AccessoriesTemplateCategory { get; set; }
        public string AccessoriesTemplateDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AccessoriesTemplateCreatedOn { get; set; }
        public string AccessoriesTemplateCreatedBy { get; set; }
        public Nullable<System.DateTime> AccessoriesTemplateUpdatedOn { get; set; }
        public string AccessoriesTemplateUpdatedBy { get; set; }
        public byte[] AccessoriesTemplateSource { get; set; }
        public string AccessoriesTemplateType { get; set; }
        public Nullable<decimal> AccessoriesTemplatePrice { get; set; }
        public string AccessoriesTemplateCode { get; set; }
    
        public virtual ICollection<Accessory> Accessories { get; set; }
        public virtual AccessoriesTemplateCategory AccessoriesTemplateCategory1 { get; set; }
    }
}
