//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoriesTemplateCategory
    {
        public AccessoriesTemplateCategory()
        {
            this.AccessoriesTemplates = new HashSet<AccessoriesTemplate>();
        }
    
        public System.Guid AccessoriesTemplateCategoryID { get; set; }
        public string AccessoriesTemplateCategoryName { get; set; }
        public string AccessoriesTemplateCategoryDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AccessoriesTemplateCategoryCreatedOn { get; set; }
        public string AccessoriesTemplateCategoryCreatedBy { get; set; }
        public Nullable<System.DateTime> AccessoriesTemplateCategoryUpdatedOn { get; set; }
        public string AccessoriesTemplateCategoryUpdatedBy { get; set; }
    
        public virtual ICollection<AccessoriesTemplate> AccessoriesTemplates { get; set; }
    }
}
