//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid AddressId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Postcode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Contact { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> AddressCreatedOn { get; set; }
        public string AddressCreatedBy { get; set; }
        public Nullable<System.DateTime> AddressUpdatedOn { get; set; }
        public string AddressUpdatedBy { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
