//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public CartItem()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public System.Guid CartListId { get; set; }
        public System.Guid CartId { get; set; }
        public System.Guid ProductId { get; set; }
        public int CartListTotalQuantity { get; set; }
        public decimal CartListTotalPrice { get; set; }
        public int CartListTotalWeight { get; set; }
        public System.DateTime CartListCreatedOn { get; set; }
        public string CartListCreatedBy { get; set; }
        public Nullable<System.DateTime> CartListUpdatedOn { get; set; }
        public string CartListUpdatedBy { get; set; }
        public System.Guid ProductColorId { get; set; }
        public Nullable<System.Guid> CustomProductID { get; set; }
    
        public virtual CustomProduct CustomProduct { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
