//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public System.Guid CartID { get; set; }
        public System.Guid CustomerID { get; set; }
        public int CartStatus { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> PaymentTotal { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentCreatedOn { get; set; }
        public string PaymentCreatedBy { get; set; }
        public System.DateTime CartCreatedOn { get; set; }
        public string CartCreatedBy { get; set; }
        public Nullable<System.DateTime> CartUpdatedOn { get; set; }
        public string CartUpdatedBy { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
