//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProductCategory { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public int CategoryStatus { get; set; }
        public System.DateTime CategoryCreateOn { get; set; }
        public string CategoryCreatedBy { get; set; }
        public Nullable<System.DateTime> CategoryUpdatedOn { get; set; }
        public string CategoryUpdatedBy { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
