//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public System.Guid CustomerCategoryId { get; set; }
        public string CustomerCategoryName { get; set; }
        public int CustomerCategoryPointGiven { get; set; }
        public int CustomerCategoryStatus { get; set; }
        public System.DateTime CustomerCategoryCreatedOn { get; set; }
        public string CustomerCategoryCreatedBy { get; set; }
        public Nullable<System.DateTime> CustomerCategoryUpdatedOn { get; set; }
        public string CustomerCategoryUpdatedBy { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
