//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public System.Guid ProductId { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<int> IsOutOfStock { get; set; }
        public System.DateTime ProductColorCreatedOn { get; set; }
        public string ProductColorCreatedBy { get; set; }
        public Nullable<System.DateTime> ProductColorUpdatedOn { get; set; }
        public string ProductColorUpdatedBy { get; set; }
        public System.Guid ProductColorId { get; set; }
        public string ProductColorValue { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
