//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string SCC_FIPS { get; set; }
        public string CC_ISO { get; set; }
        public string TLD { get; set; }
        public string COUNTRY_NAME { get; set; }
    }
}
