//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomProduct
    {
        public CustomProduct()
        {
            this.CartItems = new HashSet<CartItem>();
            this.Images = new HashSet<Image>();
        }
    
        public System.Guid CustomProductId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CustomProductCreatedOn { get; set; }
        public string CustomProductCreatedBy { get; set; }
        public Nullable<System.DateTime> CustomProductUpdatedOn { get; set; }
        public string CustomProductUpdatedBy { get; set; }
        public string Specifications { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
