//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public Folder()
        {
            this.Folders1 = new HashSet<Folder>();
            this.Products = new HashSet<Product>();
        }
    
        public System.Guid ProductFolderId { get; set; }
        public string ProductFolderName { get; set; }
        public string ProductFolderDescription { get; set; }
        public System.DateTime ProductFolderCreatedOn { get; set; }
        public string ProductFolderCreatedBy { get; set; }
        public Nullable<System.DateTime> ProductFolderUpdatedOn { get; set; }
        public string ProductFolderUpdatedBy { get; set; }
        public System.Guid ProductFolderFrom { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Folder> Folders1 { get; set; }
        public virtual Folder Folder1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
