//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public System.Guid ProductImgId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.DateTime ProductImageCreatedOn { get; set; }
        public string ProductImageCreatedBy { get; set; }
        public Nullable<System.DateTime> ProductImageUpdatedOn { get; set; }
        public string ProductImageUpdatedBy { get; set; }
        public System.Guid ProductColorId { get; set; }
        public Nullable<int> IsPrimary { get; set; }
        public string ProductImageType { get; set; }
        public byte[] ProductImageSource { get; set; }
        public Nullable<int> Status { get; set; }
        public string ProductImageName { get; set; }
        public Nullable<System.Guid> CustomProductID { get; set; }
    
        public virtual CustomProduct CustomProduct { get; set; }
        public virtual Product Product { get; set; }
    }
}
