//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastAccess
    {
        public System.Guid LastAccessId { get; set; }
        public string LastAccessLocation { get; set; }
        public string LastAccessDevice { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<System.DateTime> LastAccessCreatedOn { get; set; }
        public string LastAccessCreatedBy { get; set; }
        public Nullable<System.DateTime> LastAccessUpdatedOn { get; set; }
        public string LastAccessUpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
