//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignment
    {
        public System.Guid AssignID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid TailorID { get; set; }
        public Nullable<System.DateTime> OrderBeginTime { get; set; }
        public Nullable<System.DateTime> OrderEndTime { get; set; }
        public Nullable<decimal> CustomerReview { get; set; }
        public string Comments { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> ReviewCategory { get; set; }
        public Nullable<System.DateTime> CommentOn { get; set; }
        public string CommentBy { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tailor Tailor { get; set; }
    }
}
