//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderAssignments = new HashSet<OrderAssignment>();
        }
    
        public System.Guid OrderID { get; set; }
        public System.Guid CartListId { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDeadline { get; set; }
        public Nullable<System.DateTime> OrderCreatedOn { get; set; }
        public string OrderCreatedBy { get; set; }
        public Nullable<System.DateTime> OrderUpdatedOn { get; set; }
        public string OrderUpdatedBy { get; set; }
    
        public virtual CartItem CartItem { get; set; }
        public virtual ICollection<OrderAssignment> OrderAssignments { get; set; }
    }
}
