//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Accessories = new HashSet<Accessory>();
            this.Colors = new HashSet<Color>();
            this.CustomProducts = new HashSet<CustomProduct>();
            this.Images = new HashSet<Image>();
            this.Reviews = new HashSet<Review>();
        }
    
        public System.Guid ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int ProductCategory { get; set; }
        public int ProductQuantity { get; set; }
        public Nullable<decimal> ProductOriginalPrice { get; set; }
        public Nullable<decimal> ProductRetailPrice { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductWeight { get; set; }
        public Nullable<decimal> ProductWidth { get; set; }
        public Nullable<decimal> ProductHeight { get; set; }
        public Nullable<decimal> ProductLength { get; set; }
        public string ProductScale { get; set; }
        public Nullable<System.Guid> PromotionId { get; set; }
        public Nullable<System.Guid> ProductFolderId { get; set; }
        public int ProductStatus { get; set; }
        public System.DateTime ProductCreatedOn { get; set; }
        public string ProductCreatedBy { get; set; }
        public Nullable<System.DateTime> ProductUpdatedOn { get; set; }
        public string ProductUpdatedBy { get; set; }
        public System.Guid TemplateID { get; set; }
        public System.Guid TemplateTextureId { get; set; }
    
        public virtual ICollection<Accessory> Accessories { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<CustomProduct> CustomProducts { get; set; }
        public virtual Folder Folder { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual Texture Texture { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual Template Template { get; set; }
    }
}
