//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.Products = new HashSet<Product>();
        }
    
        public System.Guid PromotionId { get; set; }
        public string PromotionName { get; set; }
        public string PromotionDescription { get; set; }
        public byte[] PromotionImage { get; set; }
        public string PromotionBanner { get; set; }
        public Nullable<int> PromotionDiscountRate { get; set; }
        public Nullable<System.DateTime> PromotionStart { get; set; }
        public Nullable<System.DateTime> PromotionEnd { get; set; }
        public int PromotionStatus { get; set; }
        public System.DateTime PromotionCreatedOn { get; set; }
        public string PromotionCreatedBy { get; set; }
        public Nullable<System.DateTime> PromotionUpdatedOn { get; set; }
        public string PromotionUpdatedBy { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
