//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleAssigns = new HashSet<RoleAssign>();
        }
    
        public System.Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public int RoleStatus { get; set; }
        public System.DateTime RoleCreatedOn { get; set; }
        public string RoleCreatedBy { get; set; }
        public Nullable<System.DateTime> RoleUpdatedOn { get; set; }
        public string RoleUpdatedBy { get; set; }
    
        public virtual ICollection<RoleAssign> RoleAssigns { get; set; }
    }
}
