//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAssign
    {
        public System.Guid RoleAssignId { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid RoleId { get; set; }
        public System.DateTime RoleAssignCreatedOn { get; set; }
        public string RoleAssignCreatedBy { get; set; }
        public Nullable<System.DateTime> RoleAssignUpdatedOn { get; set; }
        public string RoleAssignUpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Role Role { get; set; }
    }
}
