//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tailor
    {
        public Tailor()
        {
            this.OrderAssignments = new HashSet<OrderAssignment>();
            this.Specializes = new HashSet<Specialize>();
        }
    
        public System.Guid TailorID { get; set; }
        public System.Guid CustomerID { get; set; }
        public string Specialization { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<int> AverageElapsedDay { get; set; }
        public Nullable<int> OrderInHand { get; set; }
        public Nullable<int> OrderDone { get; set; }
        public Nullable<int> GoodRev { get; set; }
        public Nullable<int> BadRev { get; set; }
        public Nullable<int> Commission { get; set; }
        public Nullable<System.DateTime> StatusUpdatedOn { get; set; }
        public string StatusUpdatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderAssignment> OrderAssignments { get; set; }
        public virtual ICollection<Specialize> Specializes { get; set; }
    }
}
