//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.Products = new HashSet<Product>();
            this.Specializes = new HashSet<Specialize>();
        }
    
        public System.Guid TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string TemplateSource { get; set; }
        public string TemplateDescription { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> TemplateCreatedOn { get; set; }
        public string TemplateCreatedBy { get; set; }
        public Nullable<System.DateTime> TemplatedUpdatedOn { get; set; }
        public string TemplateUpdatedBy { get; set; }
        public Nullable<decimal> TemplatePrice { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Specialize> Specializes { get; set; }
    }
}
