//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Texture
    {
        public Texture()
        {
            this.Products = new HashSet<Product>();
        }
    
        public System.Guid TextureId { get; set; }
        public string TextureName { get; set; }
        public byte[] TextureSource { get; set; }
        public string TextureType { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> TextureCreatedOn { get; set; }
        public string TextureCreatedBy { get; set; }
        public Nullable<System.DateTime> TextureUpdatedOn { get; set; }
        public string TextureUpdatedBy { get; set; }
        public byte[] TextureThumbnail { get; set; }
        public string TextureCode { get; set; }
        public string TextureDescription { get; set; }
        public Nullable<decimal> TexturePrice { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
