//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustomerAuthentication
    {
        public Nullable<int> CustomerCode { get; set; }
        public string CustomerPassword { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerNRIC { get; set; }
        public byte[] CustomerImg { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<int> CustomerStatus { get; set; }
        public Nullable<System.DateTime> CustomerCreatedOn { get; set; }
        public string CustomerCreatedBy { get; set; }
        public System.Guid CustomerID { get; set; }
        public string CustomerContact { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> ConfirmationStatus { get; set; }
        public string CustomerCategoryName { get; set; }
    }
}
