//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderHistory
    {
        public System.Guid OrderID { get; set; }
        public Nullable<System.DateTime> OrderCreatedOn { get; set; }
        public int OrderStatus { get; set; }
        public System.Guid CartListId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid CustomerID { get; set; }
        public System.Guid CartId { get; set; }
        public int CartListTotalQuantity { get; set; }
        public decimal CartListTotalPrice { get; set; }
        public Nullable<System.Guid> CustomProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductImageType { get; set; }
        public byte[] ProductImageSource { get; set; }
    }
}
