//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductList
    {
        public string CategoryName { get; set; }
        public string ProductColor { get; set; }
        public string ProductFolderName { get; set; }
        public byte[] ProductImg { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int ProductCategory { get; set; }
        public System.Guid ProductId { get; set; }
        public int ProductQuantity { get; set; }
        public Nullable<decimal> ProductOriginalPrice { get; set; }
        public Nullable<decimal> ProductRetailPrice { get; set; }
        public Nullable<int> IsOutOfStock { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductWeight { get; set; }
        public Nullable<decimal> ProductWidth { get; set; }
        public Nullable<decimal> ProductHeight { get; set; }
        public Nullable<decimal> ProductLength { get; set; }
        public string ProductScale { get; set; }
        public int ProductStatus { get; set; }
    }
}
