//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PopularAuthor
    {
        public System.Guid DesignerID { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public Nullable<int> SoldCount { get; set; }
    }
}
