//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECWebApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TailorPerformance
    {
        public System.Guid AssignID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid TailorID { get; set; }
        public Nullable<System.DateTime> OrderBeginTime { get; set; }
        public Nullable<System.DateTime> OrderEndTime { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<decimal> CustomerReview { get; set; }
    }
}
